=== MaxenceRoyer/TLI_Acupuncture/pathologie/pathologie.dtd
<!ELEMENT pathologie (idP, meridien, type, desc, symptomes)>
<!ELEMENT idP (#PCDATA)>
<!ELEMENT meridien (code, nom, element, yin)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT element (#PCDATA)>
<!ELEMENT yin (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT symptomes (symptome*)>
<!ELEMENT symptome (idS, desc, keywords)>
<!ELEMENT idS (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT keywords (keywords*)>
<!ELEMENT keyword (idK, name)>
<!ELEMENT idK (#PCDATA)>
<!ELEMENT name (#PCDATA)>

=== MaxenceRoyer/TLI_Acupuncture/pathologie/pathologie.xml
<?xml version="1.0"?>
<!DOCTYPE pathologie SYSTEM "pathologie.dtd">
<pathologie>
	<idP>1</idP>
	<meridien mer="P">
		<code>P</code>
		<nom>Poumon</nom>
		<element>m</element>
		<yin>1</yin>
	</meridien>
	<type>me</type>
	<desc>méridien du poumon externe</desc>
	<symptomes>
		<symptome>
			<idS>24</idS>
			<desc>Battement des ailes du nez</desc>
			<keywords>
				<keyword>
					<idK>1</idK>
					<name>\xiiE</name>
				</keyword>
				<keyword>
					<idK>2</idK>
					<name>\xxxiiE</name>
				</keyword>
				<keyword>
					<idK>3</idK>
					<name>2ème orteil</name>
				</keyword>
				<keyword>
					<idK>4</idK>
					<name>3ème orteil</name>
				</keyword>
				<keyword>
					<idK>5</idK>
					<name>4ème orteil</name>
				</keyword>
				<!-- Others results items keyword -->
			</keywords>
		</symptome>
		<symptome>
			<idS>73</idS>
			<desc>Dessèchement des phanères</desc>
			<keywords>
				<keyword>
					<idK>1</idK>
					<name>\xiiE</name>
				</keyword>
				<keyword>
					<idK>2</idK>
					<name>\xxxiiE</name>
				</keyword>
				<keyword>
					<idK>3</idK>
					<name>2ème orteil</name>
				</keyword>
				<keyword>
					<idK>4</idK>
					<name>3ème orteil</name>
				</keyword>
				<keyword>
					<idK>5</idK>
					<name>4ème orteil</name>
				</keyword>
				<!-- Others results items keyword -->
			</keywords>
		</symptome>
		<symptome>
			<idS>121</idS>
			<desc>Douleur lancinante au creux sus-claviculaire</desc>
			<keywords>
				<keyword>
					<keyword>
					<idK>1</idK>
					<name>\xiiE</name>
				</keyword>
				<keyword>
					<idK>2</idK>
					<name>\xxxiiE</name>
				</keyword>
				<keyword>
					<idK>3</idK>
					<name>2ème orteil</name>
				</keyword>
				<keyword>
					<idK>4</idK>
					<name>3ème orteil</name>
				</keyword>
				<keyword>
					<idK>5</idK>
					<name>4ème orteil</name>
				</keyword>
				<!-- Others results items keyword -->
				</keyword>
			</keywords>
		</symptome>
		<symptome>
			<idS>334</idS>
			<desc>Symptômes thoraco-pulmonaires (toux continuelle, dyspnée, gonflement thoracique)</desc>
			<keywords>
				<keyword>
					<idK>1</idK>
					<name>\xiiE</name>
				</keyword>
				<keyword>
					<idK>2</idK>
					<name>\xxxiiE</name>
				</keyword>
				<keyword>
					<idK>3</idK>
					<name>2ème orteil</name>
				</keyword>
				<keyword>
					<idK>4</idK>
					<name>3ème orteil</name>
				</keyword>
				<keyword>
					<idK>5</idK>
					<name>4ème orteil</name>
				</keyword>
				<!-- Others results items keyword -->
			</keywords>
		</symptome>
		<symptome>
			<idS>358</idS>
			<desc>Transpiration avec pollakiurie et diminution de l'appétit</desc>
			<keywords>
				<keyword>
					<idK>1</idK>
					<name>\xiiE</name>
				</keyword>
				<keyword>
					<idK>2</idK>
					<name>\xxxiiE</name>
				</keyword>
				<keyword>
					<idK>3</idK>
					<name>2ème orteil</name>
				</keyword>
				<keyword>
					<idK>4</idK>
					<name>3ème orteil</name>
				</keyword>
				<keyword>
					<idK>5</idK>
					<name>4ème orteil</name>
				</keyword>
				<!-- Others results items keyword -->
			</keywords>
		</symptome>
		<symptome>
			<idS>384</idS>
			<desc>Vue floue dans les cas graves</desc>
			<keywords>
				<keyword>
					<idK>1</idK>
					<name>\xiiE</name>
				</keyword>
				<keyword>
					<idK>2</idK>
					<name>\xxxiiE</name>
				</keyword>
				<keyword>
					<idK>3</idK>
					<name>2ème orteil</name>
				</keyword>
				<keyword>
					<idK>4</idK>
					<name>3ème orteil</name>
				</keyword>
				<keyword>
					<idK>5</idK>
					<name>4ème orteil</name>
				</keyword>
				<!-- Others results items keyword -->
			</keywords>
		</symptome>
	</symptomes>
</pathologie>
